# Generated by Django 3.2 on 2021-05-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit_name', models.CharField(choices=[('ETH', 'ethereum'), ('BTC', 'Bitcoin'), ('NEO', 'Neo_Blockchain'), ('MTL', 'metalpaysme'), ('LTC', 'litecoin'), ('XRP', 'Ripple'), ('ETC', 'eth_classic'), ('OMG', 'omgnetworkhq')], max_length=20)),
            ],
        ),
    ]
