# Generated by Django 3.2 on 2021-05-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='influencers',
            field=models.CharField(choices=[('elonmusk', 'elonmusk'), ('Kris_HK', 'Kris_HK'), ('cz_Binance', 'cz_Binance'), ('ki_young_ju', 'ki_young_ju'), ('rleshner', 'rleshner'), ('haydenzadams', 'haydenzadams'), ('balajis', 'balajis'), ('BarrySilbert', 'BarrySilbert'), ('SBF_Alameda', 'SBF_Alameda'), ('Grayscale', 'Grayscale'), ('Sonnenshein', 'Sonnenshein'), ('jack', 'jack'), ('SatoshiLite', 'SatoshiLite'), ('minhokim', 'minhokim'), ('justinsuntron', 'justinsuntron'), ('VitalikButerin', 'VitalikButerin'), ('rogerkver', 'rogerkver'), ('erikvoorhees', 'erikvoorhees'), ('brian_armstrong', 'brian_armstrong')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
