# Generated by Django 3.2 on 2021-04-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=20)),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('trade_price', models.FloatField()),
            ],
        ),
    ]
