# Generated by Django 3.2 on 2021-04-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_auto_20210430_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='coindata',
            name='acc_trade_price_24h',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
